name: Trigger Children on submodule change

on:
  push:
    branches: [ main ]
    paths:
      - "apps/**"
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Autopilot
        run: |
          set -e
          curl -sS -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GIT_PUSH_TOKEN }}" \
            https://api.github.com/repos/ibrahimalsattouf88-lab/ibrahimalsattouf88-lab-smart-assistant-autopilot/dispatches \
            -d '{"event_type":"trigger_from_meta"}'

      - name: Trigger Smart Assistant App
        run: |
          set -e
          curl -sS -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GIT_PUSH_TOKEN }}" \
            https://api.github.com/repos/ibrahimalsattouf88-lab/smart-assistant-app/dispatches \
            -d '{"event_type":"trigger_from_meta"}'

      - name: Trigger Control Panel App
        run: |
          set -e
          curl -sS -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GIT_PUSH_TOKEN }}" \
            https://api.github.com/repos/ibrahimalsattouf88-lab/control-panel-app/dispatches \
            -d '{"event_type":"trigger_from_meta"}'
